---
kind: pipeline
type: docker
name: python-minimal

steps:
- name: test
  image: python:3.8
  commands:
  - pip install --no-cache-dir -r requirements-dev.txt
  - python3 -m mypy schulze_condorcet/ tests/
  - python3 -m unittest -v tests/*.py

trigger:
  branch:
  - master

---
kind: pipeline
type: docker
name: python-recent

steps:
- name: test
  image: python
  commands:
  - pip install --no-cache-dir -r requirements-dev.txt
  - python3 -m mypy schulze_condorcet/ tests/
  - python3 -m unittest -v tests/*.py

trigger:
  branch:
  - master
  
